version: 2
defaults: &defaults
  docker:
    - image: "circleci/openjdk:11-jdk"
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      #- run:
      #    name: Run tests
      #    command: ./gradlew test
      - run:
          name: Create workspace
      command: mkdir -p /tmp/workspace
      - run:
          name: Build JAR file
          command: ./gradlew shadowJar
      - persist_to_workspace:
          root: /tmp/workspace
          paths: build/*.jar
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build and push to docker hub
          command: |
            VERSION="$(./gradlew -q printVersion)"
            GIT_HASH="$(git rev-parse HEAD)"

            echo "Extracted version = \"$VERSION\""
            echo "Extracted git hash = \"$GIT_HASH\""

            docker build -t navikt/pdfgen:latest .
            docker tag navikt/pdfgen:latest "navikt/pdfgen:$VERSION"
            docker tag navikt/pdfgen:latest "navikt/pdfgen:$GIT_HASH"

            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            docker push "navikt/pdfgen:latest"
            docker push "navikt/pdfgen:$VERSION"
            docker push "navikt/pdfgen:$GIT_HASH"

workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build
        - release:
            requires:
              - build
            filters:
              branches:
                only: master
